In [22]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [23]:
df1 = pd.read_csv('../data/query_01.csv')
df2 = pd.read_csv('../data/query_02.csv')

## 2. Inspeção inicial e qualidade dos dados

In [ ]:
# Análise exploratória dos dados

for nome, df in {
    "Query 1": df1,
    "Query 2": df2
}.items():
    print(f"\n{nome}")
    print(f"Linhas: {df.shape[0]} | Colunas: {df.shape[1]}")
    display(df.head())
    df.info()

Query 1
Linhas: 107 | Colunas: 10

,EMPLOYEE_ID,FIRST_NAME,LAST_NAME,HIRE_DATE,SALARY,DEPARTMENT_ID,DEPARTMENT_NAME,JOB_TITLE,MIN_SALARY,MAX_SALARY
0,205,Shelley,Higgins,2012-06-07T00:00:00Z,12008,110.0,Accounting,Accounting Manager,8200,16000
1,206,William,Gietz,2012-06-07T00:00:00Z,8300,110.0,Accounting,Public Accountant,4200,9000
2,200,Jennifer,Whalen,2013-09-17T00:00:00Z,4400,10.0,Administration,Administration Assistant,3000,6000
3,102,Lex,Garcia,2011-01-13T00:00:00Z,17000,90.0,Executive,Administration Vice President,15000,30000
4,101,Neena,Yang,2015-09-21T00:00:00Z,17000,90.0,Executive,Administration Vice President,15000,30000

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 107 entries, 0 to 106
Data columns (total 10 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   EMPLOYEE_ID      107 non-null    int64
 1   FIRST_NAME       107 non-null    object
 2   LAST_NAME        107 non-null    object
 3   HIRE_DATE        107 non-null    object
 4   SALARY           107 non-null    int64
 5   DEPARTMENT_ID    106 non-null    float64
 6   DEPARTMENT_NAME  106 non-null    object
 7   JOB_TITLE        107 non-null    object
 8   MIN_SALARY       107 non-null    int64
 9   MAX_SALARY       107 non-null    int64
dtypes: float64(1), int64(4), object(5)
memory usage: 8.5+ KB

Query 2
Linhas: 107 | Colunas: 14

,EMPLOYEE_ID,FIRST_NAME,LAST_NAME,HIRE_DATE,SALARY,DEPARTMENT_ID,DEPARTMENT_NAME,LOCATION_ID,CITY,STATE_PROVINCE,COUNTRY_ID,COUNTRY_NAME,REGION_ID,REGION_NAME
0,201,Michael,Martinez,2014-02-17T00:00:00Z,13000,20.0,Marketing,1800.0,Toronto,Ontario,CA,Canada,20.0,Americas
1,202,Pat,Davis,2015-08-17T00:00:00Z,6000,20.0,Marketing,1800.0,Toronto,Ontario,CA,Canada,20.0,Americas
2,100,Steven,King,2013-06-17T00:00:00Z,24000,90.0,Executive,1700.0,Seattle,Washington,US,United States of America,20.0,Americas
3,101,Neena,Yang,2015-09-21T00:00:00Z,17000,90.0,Executive,1700.0,Seattle,Washington,US,United States of America,20.0,Americas
4,102,Lex,Garcia,2011-01-13T00:00:00Z,17000,90.0,Executive,1700.0,Seattle,Washington,US,United States of America,20.0,Americas

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 107 entries, 0 to 106
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   EMPLOYEE_ID      107 non-null    int64
 1   FIRST_NAME       107 non-null    object
 2   LAST_NAME        107 non-null    object
 3   HIRE_DATE        107 non-null    object
 4   SALARY           107 non-null    int64
 5   DEPARTMENT_ID    106 non-null    float64
 6   DEPARTMENT_NAME  106 non-null    object
 7   LOCATION_ID      106 non-null    float64
 8   CITY             106 non-null    object
 9   STATE_PROVINCE   105 non-null    object
 10  COUNTRY_ID       106 non-null    object
 11  COUNTRY_NAME     106 non-null    object
 12  REGION_ID        106 non-null    float64
 13  REGION_NAME      106 non-null    object
dtypes: float64(3), int64(2), object(9)
memory usage: 11.8+ KB

In [ ]:
# Verificando valores ausentes e duplicados

for nome, df in {
    "Query 1": df1,
    "Query 2": df2
}.items():
    print(f"\n{nome}")
    display(df.isna().sum().rename("Valores ausentes"))
    print("Linhas duplicadas:", df.duplicated().sum())

Query 1

EMPLOYEE_ID        0
FIRST_NAME         0
LAST_NAME          0
HIRE_DATE          0
SALARY             0
DEPARTMENT_ID      1
DEPARTMENT_NAME    1
JOB_TITLE          0
MIN_SALARY         0
MAX_SALARY         0
Name: Valores ausentes, dtype: int64

Linhas duplicadas: 0

Query 2

EMPLOYEE_ID        0
FIRST_NAME         0
LAST_NAME          0
HIRE_DATE          0
SALARY             0
DEPARTMENT_ID      1
DEPARTMENT_NAME    1
LOCATION_ID        1
CITY               1
STATE_PROVINCE     2
COUNTRY_ID         1
COUNTRY_NAME       1
REGION_ID          1
REGION_NAME        1
Name: Valores ausentes, dtype: int64

Linhas duplicadas: 0

In [ ]:
# Conversão de tipos de dados

for df in [df1, df2]:
    df['HIRE_DATE'] = pd.to_datetime(df['HIRE_DATE'], errors='coerce')
    
for coluna in ["EMPLOYEE_ID", "DEPARTMENT_ID"]:
    df1[coluna] = pd.to_numeric(
        df1[coluna],
        errors="coerce"
    ).astype("Int64")
    
for coluna in [
    "EMPLOYEE_ID",
    "DEPARTMENT_ID",
    "LOCATION_ID",
    "REGION_ID"
]:
    df2[coluna] = pd.to_numeric(
        df2[coluna],
        errors="coerce"
    ).astype("Int64")


df1.info()
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 107 entries, 0 to 106
Data columns (total 10 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   EMPLOYEE_ID      107 non-null    Int64
 1   FIRST_NAME       107 non-null    object
 2   LAST_NAME        107 non-null    object
 3   HIRE_DATE        107 non-null    datetime64[ns, UTC]
 4   SALARY           107 non-null    int64
 5   DEPARTMENT_ID    106 non-null    Int64
 6   DEPARTMENT_NAME  106 non-null    object
 7   JOB_TITLE        107 non-null    object
 8   MIN_SALARY       107 non-null    int64
 9   MAX_SALARY       107 non-null    int64
dtypes: Int64(2), datetime64[ns, UTC](1), int64(3), object(4)
memory usage: 8.7+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 107 entries, 0 to 106
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   EMPLOYEE_ID      107 non-null    Int64
 1   FIRST_NAME       107 non-null    object
 2   LAST_NAME        107 non-null    object
 3   HIRE_DATE        107 non-null    datetime64[ns, UTC]
 4   SALARY           107 non-null    int64
 5   DEPARTMENT_ID    106 non-null    Int64
 6   DEPARTMENT_NAME  106 non-null    object
 7   LOCATION_ID      106 non-null    Int64
 8   CITY             106 non-null    object
 9   STATE_PROVINCE   105 non-null    object
 10  COUNTRY_ID       106 non-null    object
 11  COUNTRY_NAME     106 non-null    object
 12  REGION_ID        106 non-null    Int64
 13  REGION_NAME      106 non-null    object
dtypes: Int64(4), datetime64[ns, UTC](1), int64(1), object(8)
memory usage: 12.2+ KB